name: Deploy web to production

on:
  push:
    branches:
      - main

concurrency:
  cancel_in_progress: true
  group: ${{ workflow.filename }}-${{ github.ref }}

jobs:
  deploy_web:
    name: Deploy web to production
    type: deploy
    params:
      prod: true
